### ISSUE TITLE
Wrong extension upload in TER

### ISSUE THREAD

**Issue by rr-it** [sudhaus7/typo3-picture#3]
Somehow in TER the latest extension version is not `responsive_picture` but is `xlsimport`:
see https://extensions.typo3.org/extension/responsive_picture

**Comment by foppelfb** [comment]
Well well, Mr. Hofmann had a wrong extension key in the other extension.. Thanks for pointing out

**Comment by foppelfb** [comment]
Pushed a new version, should fix itself within the hour. Thanks again
